コーディング規約とgithubの運用手順を記載
aistaticer/picture_battle pull request #2
Opened 2024-12-28 00:26 UTC by aistaticer

差分としては出てこない箇所もありますが、coding-guidelines.mdとgit-workflow.mdの全行の確認をお願いします。
誤ったコミット方法を使用し、差分として表示できなくなりました。

2025-01-06 14:53 UTC, yoshi5170 requested changes

2025-01-06 14:53 UTC, yoshi5170 commented on coding-guidelines.md
> +- ハードコーディングの禁止
```suggestion
- SQL分にはプレースホルダーを使用する
```
SQLインジェクション対策として必要だと感じました。

2025-01-06 14:53 UTC, yoshi5170 commented on coding-guidelines.md
Javadocを使用してメソッドの説明を記述するをガイドラインの方に追加をお願いいたします。

2025-01-06 14:53 UTC, yoshi5170 commented on coding-guidelines.md
> +- 再代入が必要な場合は、コメントなどでその理由を補足。
この処理を行う理由を教えていただけますでしょうか？
コードの意図が明らかである場合はコメントは必要ないと感じました。
例えば：
```
User user = new User();
user = userService.save(user);
```

2025-01-06 14:53 UTC, yoshi5170 commented on git-workflow.md
`リモートにpush`部分について
現状毎回リモートのdevelopブランチにプッシュする形になっていますが、変更後のやり方の認識でしたのでご確認のほどよろしくお願いいたします。
変更前
```
git push origin develop
```

変更後
```
git push origin <作業ブランチ名>
```

2025-01-06 14:53 UTC, yoshi5170 commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
こちらはマージではなくリモートブランチからプルするという認識でした。

2025-01-06 14:53 UTC, yoshi5170 commented on git-workflow.md
>  git merge feature/login
こちらもマージではなくリモートブランチからプルするという認識でした。

2025-01-06 14:53 UTC, yoshi5170 commented on git-workflow.md
`問題がなければmainブランチを最新に更新`の部分について
以下の変更後のような流れを想定しておりました。
変更前
```
git switch main
git pull origin main
```
変更後
```
git switch main
git pull origin develop
```

2025-01-06 14:53 UTC, yoshi5170 commented on git-workflow.md
`developブランチに移動してdevelopブランチに特定のブランチをマージ`について
以下の変更後のような流れを想定しておりました。
変更前
```
git switch develop
git switch develop　
git merge feature/login
```

変更後
```
git switch develop
git pull origin develop
```

2025-01-13 15:00 UTC, aistaticer commented on coding-guidelines.md
> +- ハードコーディングの禁止
SQLインジェクション対策を追加しました。

[SQLインジェクション対策追加部分]
(https://github.com/aistaticer/picture_battle/commit/491a1dead97af1596e17063263a2acfd0397da16#diff-77d81c5aa9bbe9d52133046105e1641f211f6000cc8db57858b072ff4808c77eR59-R63)

2025-01-13 15:04 UTC, aistaticer commented on coding-guidelines.md
Javadocを使用する旨を記載しました。
それに付随してコメントの方にもJavadocのコメントの仕方を追記しました。
[Javadoc追記部分](https://github.com/aistaticer/picture_battle/commit/491a1dead97af1596e17063263a2acfd0397da16#diff-77d81c5aa9bbe9d52133046105e1641f211f6000cc8db57858b072ff4808c77eR11-R26)

2025-01-13 15:07 UTC, aistaticer commented on coding-guidelines.md
> +- 再代入が必要な場合は、コメントなどでその理由を補足。
その方がわかりやすいかと思いました確かに意図が明確なら必要ないと考え直したため該当箇所を削除しました。

[該当削除箇所](https://github.com/aistaticer/picture_battle/commit/491a1dead97af1596e17063263a2acfd0397da16#diff-77d81c5aa9bbe9d52133046105e1641f211f6000cc8db57858b072ff4808c77eR41-R45)

2025-01-13 15:20 UTC, aistaticer commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
pullコマンドを実行すると意図しない競合の解決を引き起こす場合があるそうなのでfetchでリモートのファイル情報を認識させてからmergeで取り込むという形にしたいなと思ったのですがどうでしょうか？

[変更した部分](https://github.com/aistaticer/picture_battle/commit/491a1dead97af1596e17063263a2acfd0397da16#diff-53d71dd23bf32332925379eb520b5915cb953cb32a8e1e1889e784422be48474R60-R64)

2025-01-13 15:22 UTC, aistaticer commented on git-workflow.md
>  git merge feature/login
こちらの回答と同じ回答になります。

https://github.com/aistaticer/picture_battle/pull/2#discussion_r1904237147

2025-01-14 13:46 UTC, yoshi5170 commented on git-workflow.md
>  git merge feature/login
上記と同じ質問になります

2025-01-14 14:00 UTC, yoshi5170 commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
いきなりfeature/loginブランチの操作から始まっていて流れが掴めないので、前提情報の提示をお願いいたします。

2025-01-14 14:58 UTC, aistaticer commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
# 3. developブランチへのマージ手順及びリモートへの反映手順
は開発ブランチ(例で言うとfeature/loginブランチ)に変更を加えた時にリモートに反映することを目的としています。

そのためfeature/loginブランチに他人が変更を加えた可能性を見越してリモートの変更を取り込む操作を最初に入れました。

2025-01-14 14:59 UTC, aistaticer commented on git-workflow.md
>  git merge feature/login
下記と同じ回答になります。

https://github.com/aistaticer/picture_battle/pull/2#discussion_r1914978793

2025-01-14 15:07 UTC, aistaticer commented on git-workflow.md
プルリク前のpush先が誤っていたため修正しました。

https://github.com/aistaticer/picture_battle/blob/491a1dead97af1596e17063263a2acfd0397da16/git-workflow.md?plain=1#L81-L84

2025-01-14 15:17 UTC, aistaticer commented on git-workflow.md
指摘とは異なる形ですがローカルのmainブランチにリモートのブランチを反映させる手順を変更しました。

https://github.com/aistaticer/picture_battle/blob/491a1dead97af1596e17063263a2acfd0397da16/git-workflow.md?plain=1#L106-L111

2025-01-14 15:31 UTC, aistaticer commented on git-workflow.md
こちらですがfeature/loginブランチに最初にpushしなければいけないという前提を誤っていました。

```
git switch develop
git pull origin develop
```
こちらと同様にdevelopブランチをローカルに反映させる手順は以下のように記載いたしました。

https://github.com/aistaticer/picture_battle/blob/491a1dead97af1596e17063263a2acfd0397da16/git-workflow.md?plain=1#L94-L100

2025-01-14 16:43 UTC, aistaticer commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
すいません、思い直したんですが開発ブランチは操作する人間が一人だけで、別にリモートの開発ブランチをマージしてくる必要はないのでしょうか？
でしたら
https://github.com/aistaticer/picture_battle/blob/491a1dead97af1596e17063263a2acfd0397da16/git-workflow.md?plain=1#L40-L73
の箇所を削除しようかと思います

2025-01-15 13:26 UTC, yoshi5170 commented on git-workflow.md
以下だとリモートのmainブランチの情報を取得してしまっていると思います。
```
git fetch origin
```
もしリモートのdevelopブランチの情報を取得したい場合は以下のコマンドを実行する必要があるかと思います。
```
git fetch origin develop
```

2025-01-15 13:51 UTC, yoshi5170 commented on git-workflow.md
>  - developブランチに移動してdevelopブランチに特定のブランチをマージ
上記の操作は不要な気がします。

developブランチのマージは以下のような流れになると思います。

1. 以下のブランチを指定してPRを出す
develop　<-  feature/login

3. レビューがOKの場合mergeボタンをクリック
2.  リモートのdevelop（feature/loginの内容が反映されている状態）ブランチをローカルのdevelopブランチ（feature/loginの内容がまだ反映されていない状態）に反映
```
git fetch develop
git switch develop
git merge origin develop
````


>思い直したんですが開発ブランチは操作する人間が一人だけで、別にリモートの開発ブランチをマージしてくる必要はないのでしょうか？
この部分の説明がよりわからないのでもう少ししわかりやすく説明をお願いします。
- 開発ブランチは操作する人間が一人だけとはどういうことですか？
- リモートの開発ブランチをマージの部分はどこのブランチへのマージを指していますか？

2025-01-25 00:44 UTC, aistaticer commented
3. developブランチへのマージ手順及びリモートへの反映手順を3. コンフリクト解消手順、4. プルリク手順の二つに分割しました。

https://github.com/aistaticer/picture_battle/blob/fb8e4d17203df912a732bcdf335b4ddca916009b/git-workflow.md?plain=1#L65-L73
コンフリクト解消後のマージコマンドがなかったので書き足しました。

2025-03-31 18:25 UTC, closed without merging